modLoader="javafml" # 必填
loaderVersion="[47,)" # Forge 47.x 都能运行

license="MIT with Non-Commercial clause"

[[mods]]
modId="xulielizimod"   # 必须和 @Mod("xulielizimod") 一致
version="1.0.0"
displayName="彬的序列粒子"
displayURL="https://space.bilibili.com/353609880"
authors="XiaoBiniaoX"
description='''补药商用啊啊啊.'''

[[dependencies.xulielizimod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xulielizimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
